version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Test
          command: cargo run --release -- -p && cargo test --release && cargo test --release -- --ignored
          no_output_timeout: 1200
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

